/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Text;
export const MessageStatus = IDL.Variant({
  'read' : IDL.Null,
  'sent' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const MessageType = IDL.Variant({
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileType = IDL.Variant({
  'video' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const MediaFile = IDL.Record({
  'media' : ExternalBlob,
  'fileType' : FileType,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'content' : IDL.Text,
  'deliveryTime' : IDL.Opt(Time),
  'readTime' : IDL.Opt(Time),
  'messageType' : MessageType,
  'conversationId' : IDL.Text,
  'mediaFile' : IDL.Opt(MediaFile),
  'timestamp' : Time,
  'senderId' : IDL.Text,
});
export const ConversationType = IDL.Variant({
  'group' : IDL.Null,
  'oneOnOne' : IDL.Null,
});
export const ConversationView = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'messages' : IDL.Vec(Message),
  'name' : IDL.Text,
  'admins' : IDL.Opt(IDL.Vec(IDL.Text)),
  'timestamp' : Time,
  'conversationType' : ConversationType,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'statusMessage' : IDL.Opt(IDL.Text),
  'lastSeen' : Time,
});
export const CreateUserResult = IDL.Variant({
  'authenticationError' : IDL.Text,
  'userProfile' : UserProfile,
  'usernameTaken' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminAssignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroupChat' : IDL.Func(
      [IDL.Vec(UserId), IDL.Text],
      [ConversationView],
      [],
    ),
  'createOneOnOneConversation' : IDL.Func([UserId], [ConversationView], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [CreateUserResult], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactById' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getConversation' : IDL.Func([IDL.Text], [IDL.Opt(ConversationView)], []),
  'getMessages' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      [],
    ),
  'getMyConversations' : IDL.Func([], [IDL.Vec(ConversationView)], []),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsDelivered' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'markMessageAsRead' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, MessageType, IDL.Opt(MediaFile)],
      [Message],
      [],
    ),
  'updateLastSeen' : IDL.Func([], [], []),
  'uploadMedia' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Text;
  const MessageStatus = IDL.Variant({
    'read' : IDL.Null,
    'sent' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const MessageType = IDL.Variant({
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileType = IDL.Variant({
    'video' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const MediaFile = IDL.Record({
    'media' : ExternalBlob,
    'fileType' : FileType,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'content' : IDL.Text,
    'deliveryTime' : IDL.Opt(Time),
    'readTime' : IDL.Opt(Time),
    'messageType' : MessageType,
    'conversationId' : IDL.Text,
    'mediaFile' : IDL.Opt(MediaFile),
    'timestamp' : Time,
    'senderId' : IDL.Text,
  });
  const ConversationType = IDL.Variant({
    'group' : IDL.Null,
    'oneOnOne' : IDL.Null,
  });
  const ConversationView = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'messages' : IDL.Vec(Message),
    'name' : IDL.Text,
    'admins' : IDL.Opt(IDL.Vec(IDL.Text)),
    'timestamp' : Time,
    'conversationType' : ConversationType,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'statusMessage' : IDL.Opt(IDL.Text),
    'lastSeen' : Time,
  });
  const CreateUserResult = IDL.Variant({
    'authenticationError' : IDL.Text,
    'userProfile' : UserProfile,
    'usernameTaken' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminAssignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroupChat' : IDL.Func(
        [IDL.Vec(UserId), IDL.Text],
        [ConversationView],
        [],
      ),
    'createOneOnOneConversation' : IDL.Func([UserId], [ConversationView], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [CreateUserResult], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactById' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getConversation' : IDL.Func([IDL.Text], [IDL.Opt(ConversationView)], []),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        [],
      ),
    'getMyConversations' : IDL.Func([], [IDL.Vec(ConversationView)], []),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsDelivered' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'markMessageAsRead' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, MessageType, IDL.Opt(MediaFile)],
        [Message],
        [],
      ),
    'updateLastSeen' : IDL.Func([], [], []),
    'uploadMedia' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };